### PR TITLE
add just to the bieberLovePattern

### PR DESCRIPTION
**Pull request by danielravina**
After a thorough user test, we came to the conclusion that people don't really love JB, they _just_ love JB. this fix will make JB to _just_ love them back.

### CODE REVIEW

**Comment by pmoghaddam** [comment]
:shipit:

**Comment by danielravina** [comment]
is that an 🆗  @pmoghaddam :) ?

**Comment by pmoghaddam** [comment]
Ahaha, yes sir @danielravina 🆗

**Comment by nielmclaren** [comment]
lgtm roland dance

**Pull request merged**
